version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g @quasar/cli
      - npm install

  pre_build:
    commands:
      - quasar build

artifacts:
  files:
    - dist/**/*

post_build:
    commands:
      - echo Build completed on `date`

cache:
  paths:
    - node_modules/