version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Buile Phase >> pre_build phase...
  build:
    commands:
      - echo Buile Phase >> Build started on `date`
      - npm i -g @quasar/cli
      - npm install
      - quasar build
  post_build:
    commands:
      - echo Buile Phase >> Build completed on `date`
artifacts:
  files:
    - dist/**/*