version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
      commands:
      - echo Install Source NPM
      - npm i -g @quasar/cli
      - npm install
  pre_build:
    commands:
      - echo Buile Phase >> pre_build phase...
 
  build:
    commands:
      - echo Buile Phase >> Build started on `date`
      - quasar build
 
  post_build:
    commands:
      - echo Buile Phase >> Build completed on `date`

artifacts:
  files:
    - dist/**/*